import assets from "./assets";

const NFTData = [
  {
    id: "NFT-01",
    name: "Bored Ape",
    creator: "Sedinam",
    price: 10.25,
    description:
      "Bored Ape Yacht Club (BAYC), or often colloquially called Bored Apes or Bored Ape, is a non-fungible token (NFT) collection built on the Ethereum blockchain. The collection features profile pictures of cartoon apes that are procedurally generated by an algorithm.",
    image: assets.nft01,
    bids: [
      {
        id: "BID-11",
        name: "Jeffrey Boafo",
        price: 4.25,
        image: assets.person02,
        date: "October 15, 2022 at 11:45 AM",
      },
      {
        id: "BID-12",
        name: "Deladem Harlley",
        price: 4.5,
        image: assets.person03,
        date: "October 10, 2022 at 11:45 AM",
      },
      {
        id: "BID-13",
        name: "Collins Gasoe",
        price: 4.75,
        image: assets.person04,
        date: "October 11, 2022 at 11:45 AM",
      },
    ],
  },
  {
    id: "NFT-02",
    name: "So Much Fun",
    creator: "Deladem",
    price: 7.25,
    description:"So Much Fun is the debut studio album by American rapper Young Thug. It was released on August 16, 2019, by YSL Records, 300 Entertainment and Atlantic Records",
    image: assets.nft02,
    bids: [
      {
        id: "BID-21",
        name: "Wade Khaleed",
        price: 7.05,
        image: assets.person04,
        date: "October 12, 2022 at 12:10 PM",
      },
    ],
  },
  {
    id: "NFT-03",
    name: "Manila",
    creator: "Justice",
    price: 95.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.nft03,
    bids: [
      {
        id: "BID-31",
        name: "Favour Ovuike",
        price: 95.25,
        image: assets.person02,
        date: "October 1, 2022 at 12:08 PM",
      },
      {
        id: "BID-32",
        name: "Huldah Shaw",
        price: 95.5,
        image: assets.person03,
        date: "October 13, 2022 at 1:50 PM",
      },
    ],
  },
  {
    id: "NFT-04",
    name: "Rick and Morty NFT",
    creator: "Selorm",
    price: 54.25,
    description:
      "Rick, an alcoholic sociopath and scientist, lives with his daughter Beth's family. Apart from building gadgets, he takes his morally right but dimwit grandson Morty on absurd intergalactic adventures.",
    image: assets.nft04,
    bids: [
      {
        id: "BID-41",
        name: "Olivia Jones",
        price: 56.25,
        image: assets.person02,
        date: "October 8, 2022 at 03:10 PM",
      },
      {
        id: "BID-42",
        name: "Trisha Boafo",
        price: 54.25,
        image: assets.person03,
        date: "October 8, 2022 at 04:10 PM",
      },
      {
        id: "BID-43",
        name: "Sika Elizabeth",
        price: 55.15,
        image: assets.person04,
        date: "October 8, 2022 at 05:10 PM",
      },
      {
        id: "BID-44",
        name: "Richard Wilson",
        price: 54.15,
        image: assets.person02,
        date: "October 8, 2022 at 09:10 PM",
      },
    ],
  },
  {
    id: "NFT-05",
    name: "Call of Duty Cold War",
    creator: "Wade Khaleef",
    price: 10.25,
    description:
      "Call of Duty: Black Ops Cold War is a 2020 first-person shooter video game developed by Treyarch and Raven Software and published by Activision.",
    image: assets.nft05,
    bids: [
      {
        id: "BID-51",
        name: "Gabriel Sedinam",
        price: 10.25,
        image: assets.person02,
        date: "October 02, 2022 at 12:10 PM",
      },
    ],
  },
  {
    id: "NFT-06",
    name: "Focused Eye NFT",
    creator: "Jhay",
    price: 20.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis.",
    image: assets.nft06,
    bids: [
      {
        id: "BID-61",
        name: "Gabriel Sedinam",
        price: 20.25,
        image: assets.person02,
        date: "October 12, 2022 at 12:30 PM",
      },
      {
        id: "BID-62",
        name: "Deladem Harlley",
        price: 20.5,
        image: assets.person03,
        date: "October 2, 2022 at 2:30 PM",
      },
      {
        id: "BID-63",
        name: "Huldah Shaw",
        price: 20.75,
        image: assets.person04,
        date: "October 12, 2022 at 03:30 PM",
      },
      {
        id: "BID-64",
        name: "Favour Ovuike",
        price: 21.25,
        image: assets.person02,
        date: "October 12, 2022 at 12:39 PM",
      },
      {
        id: "BID-65",
        name: "Luqman Ansah",
        price: 7.25,
        image: assets.person02,
        date: "October 6, 2022 at 2:36 PM",
      },
    ],
  },
  {
    id: "NFT-07",
    name: "Abstracto soulful art",
    creator: "Luqman Ansah",
    price: 18.25,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
    image: assets.nft07,
    bids: [],
  },
];

export { NFTData };
